- name: download ansible awx from git for test
  hosts: all
  tasks:
    - name: git clone ansible awx
      git:
        repo: https://github.com/ansible/awx.git
        dest: ~/git_download_test
        clone: yes
        update: yes
    
    - name: show message for finish
      ansible.builtin.debug:
        msg: git clone is done
